name: test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: jdx/mise-action@v3
        with:
          install: true
          cache: true

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: format
        run: bun run format

      - name: typecheck
        run: bun run typecheck

      - name: lint
        run: bun run lint

      - name: Unit tests
        run: bun run test
